image: archlinux
packages:
  - go
sources:
  - https://github.com/mariusor/feeds
tasks:
  - setup: |
      cd feeds && make download && go mod vendor
  - build: |
      cd feeds
      make clean all

