INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/1/Mother-of-Learning', '1. Good Morning Brother', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/2/Mother-of-Learning', '2. Life''s Little Problems', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/3/Mother-of-Learning', '3. The Bitter Truth', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/4/Mother-of-Learning', '4. Stars Fell', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/5/Mother-of-Learning', '5. Start Over', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/6/Mother-of-Learning', '6. Concentrate And Try Again', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/7/Mother-of-Learning', '7. Of Gaps And Pretending', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/8/Mother-of-Learning', '8. Perspective', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/9/Mother-of-Learning', '9. Cheaters', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/10/Mother-of-Learning', '10. Overlooked Details', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/11/Mother-of-Learning', '11. Limiters', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/12/Mother-of-Learning', '12. Soul Web', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/13/Mother-of-Learning', '13. Any Second Now', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/14/Mother-of-Learning', '14. The Sister Effect', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/15/Mother-of-Learning', '15. Busy Friday', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/16/Mother-of-Learning', '16. We Need To Talk', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/17/Mother-of-Learning', '17. Sympathy for the Spider', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/18/Mother-of-Learning', '18. The Pact Is Sealed', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/19/Mother-of-Learning', '19. Tangled Webs', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/20/Mother-of-Learning', '20. A Matter of Faith', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/21/Mother-of-Learning', '21. Wheel of Fortune', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/22/Mother-of-Learning', '22. Complications', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/23/Mother-of-Learning', '23. Lighting the Fuse', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/24/Mother-of-Learning', '24. Smoke and Mirrors', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/25/Mother-of-Learning', '25. The Unexpected', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/26/Mother-of-Learning', '26. Soulkill', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/27/Mother-of-Learning', '27. Cast Adrift', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/28/Mother-of-Learning', '28. Cauldron', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/29/Mother-of-Learning', '29. The Hunter and the Hunted', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/30/Mother-of-Learning', '30. A Game of Shops', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/31/Mother-of-Learning', '31. Marked', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/32/Mother-of-Learning', '32. Alternatives', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/33/Mother-of-Learning', '33. Gateways', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/34/Mother-of-Learning', '34. Unreasonable Things', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/35/Mother-of-Learning', '35. Mistakes Have Been Made', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/36/Mother-of-Learning', '36. A Battle of Minds', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/37/Mother-of-Learning', '37. Slow Burn', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/38/Mother-of-Learning', '38. Return to Cyoria', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/39/Mother-of-Learning', '39. Suspicious Coincidences', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/40/Mother-of-Learning', '40. Shifting Tracks', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/41/Mother-of-Learning', '41. Myriad Clashing Motives', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/42/Mother-of-Learning', '42. Sum of Its Parts', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/43/Mother-of-Learning', '43. Overwhelmed', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/44/Mother-of-Learning', '44. A Show of Trust', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/45/Mother-of-Learning', '45. Fine Structures', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/46/Mother-of-Learning', '46. The Other Side', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/47/Mother-of-Learning', '47. Politics', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/48/Mother-of-Learning', '48. Well of Souls', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/49/Mother-of-Learning', '49. Substitution', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/50/Mother-of-Learning', '50. Containment', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/51/Mother-of-Learning', '51. Out of Control', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/52/Mother-of-Learning', '52. Things Fall Apart', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/53/Mother-of-Learning', '53. Phantoms', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/54/Mother-of-Learning', '54. The Gate Is Barred', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/55/Mother-of-Learning', '55. Threshold', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/56/Mother-of-Learning', '56. Obscure', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/57/Mother-of-Learning', '57. Unwanted', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/58/Mother-of-Learning', '58. Questions and Answers', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/59/Mother-of-Learning', '59. One Step Forward', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/60/Mother-of-Learning', '60. Into the Abyss', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/61/Mother-of-Learning', '61. Anthills', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/62/Mother-of-Learning', '62. Improperly Used', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/63/Mother-of-Learning', '63. The March of Days', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/64/Mother-of-Learning', '64. Distance', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/65/Mother-of-Learning', '65. Dangerous Ground', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/66/Mother-of-Learning', '66. Marred Perfection', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/67/Mother-of-Learning', '67. Convergence', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/68/Mother-of-Learning', '68. Green Hell', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/69/Mother-of-Learning', '69. Ruin', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/70/Mother-of-Learning', '70. Carried Away', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/71/Mother-of-Learning', '71. Shadows of the Past', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/72/Mother-of-Learning', '72. Crossroads', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/73/Mother-of-Learning', '73. Plodding Ahead', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/74/Mother-of-Learning', '74. The Return', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/75/Mother-of-Learning', '75. Soul Stealer', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/76/Mother-of-Learning', '76. Critical Blunder', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/77/Mother-of-Learning', '77. Testing', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/78/Mother-of-Learning', '78. Grinding Stone', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/79/Mother-of-Learning', '79. Crime and Evading Punishment', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/80/Mother-of-Learning', '80. Enemies', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/81/Mother-of-Learning', '81. A Civil Conversation', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/82/Mother-of-Learning', '82. Ancient Circles', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/83/Mother-of-Learning', '83. Scorpion', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/84/Mother-of-Learning', '84. Powerless', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/85/Mother-of-Learning', '85. Critical Mass', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/86/Mother-of-Learning', '86. A New World', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/87/Mother-of-Learning', '87. Agents of the Crown', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/88/Mother-of-Learning', '88. Mysterious Ways', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/89/Mother-of-Learning', '89. Victory', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/90/Mother-of-Learning', '90. Change of Plans', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/91/Mother-of-Learning', '91. A Path Paid in Blood', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/92/Mother-of-Learning', '92. The Scramble', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/93/Mother-of-Learning', '93. Shelter in the Storm', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/94/Mother-of-Learning', '94. Ghosts', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/95/Mother-of-Learning', '95. Betrayer', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/96/Mother-of-Learning', '96. Contract', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/97/Mother-of-Learning', '97. Illusory', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/98/Mother-of-Learning', '98. Beneath the Surface', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/99/Mother-of-Learning', '99. Powderkeg', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/100/Mother-of-Learning', '100. Sacrifice', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/101/Mother-of-Learning', '101. The Switch', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/102/Mother-of-Learning', '102. Giants', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/103/Mother-of-Learning', '103. Window of Opportunity', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/104/Mother-of-Learning', '104. I Win (I)', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/105/Mother-of-Learning', '105. I Win (II)', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/106/Mother-of-Learning', '106. I Win (III)', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/107/Mother-of-Learning', '107. Epilogue', 5, 'Nobody103');
INSERT INTO items (url, title, feed_id, author) values ('https://www.fictionpress.com/s/2961893/108/Mother-of-Learning', '108. Afterword', 5, 'Nobody103');
