insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/10/back-away-5-3/', 'Pale: Back Away – 5.3', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/08/5-2-spoilers-faerie-courts-goblins/', 'Pale: [5.2 Spoilers] Faerie Courts & Goblins', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/06/back-away-5-2/', 'Pale: Back Away – 5.2', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/03/back-away-5-1/', 'Pale: Back Away – 5.1', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/01/5-b-spoilers-phone-conversations/', 'Pale: [5.b Spoilers] Phone Conversations', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/09/29/back-away-5-b/', 'Pale: Back Away – 5.b', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/09/26/back-away-5-a/', 'Pale: Back Away – 5.a', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/09/24/4-10-spoilers-spell-notes-3/', 'Pale: [4.10 Spoilers] Spell Notes #3', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/09/22/leaving-a-mark-4-10/', 'Pale: Leaving a Mark – 4.10', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/09/19/leaving-a-mark-4-9/', 'Pale: Leaving a Mark – 4.9', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/13/back-away-5-4/', 'Pale: Back Away – 5.4', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/15/5-4-spoilers-outgoing-call/', 'Pale: [5.4 Spoilers] Outgoing Call', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/17/back-away-5-c/', 'Pale: Back Away – 5.c', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/20/back-away-5-5/', 'Pale: Back Away – 5.5', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/22/5-5-spoilers-kennet-newsletter/', 'Pale: [5.5 Spoilers] Kennet Newsletter', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/24/back-away-5-d/', 'Pale: Back Away – 5.d', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/27/cutting-class-6-1/', 'Pale: Cutting Class – 6.1', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/29/6-1-spoilers-famulus-text/', 'Pale: [6.1 Spoilers] Famulus Text', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/10/31/cutting-class-6-2/', 'Pale: Cutting Class – 6.2', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/03/cutting-class-6-3/', 'Pale: Cutting Class – 6.3', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/05/6-3-spoilers-implementum-text/', 'Pale: [6.3 Spoilers] Implementum Text', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/07/cutting-class-6-4/', 'Pale: Cutting Class – 6.4', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/10/cutting-class-6-5/', 'Pale: Cutting Class – 6.5', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/12/demesnes-text/', 'Pale: Demesnes Text', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/14/cutting-class-6-6/', 'Pale: Cutting Class – 6.6', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/17/cutting-class-6-7/', 'Pale: Cutting Class – 6.7', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/19/temporary-post-no-extra-materials/', 'Pale: [Temporary Post] – No Extra Materials', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/21/cutting-class-6-8/', 'Pale: Cutting Class – 6.8', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/24/cutting-class-6-9/', 'Pale: Cutting Class – 6.9', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/26/6-9-spoilers-binding-countermeasures/', 'Pale: [6.9 Spoilers] Binding & Countermeasures', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/11/28/cutting-class-6-z/', 'Pale: Cutting Class – 6.z', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/01/gone-ahead-7-1/', 'Pale: Gone Ahead – 7.1', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/03/temporary-no-extra-materials/', 'Pale: [Temporary] No Extra Materials', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/05/gone-ahead-7-2/', 'Pale: Gone Ahead – 7.2', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/08/gone-ahead-7-3/', 'Pale: Gone Ahead – 7.3', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/10/7-3-spoilers-borrowed-eyes-comic/', 'Pale: [7.3 Spoilers] – Borrowed Eyes Comic', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/12/gone-ahead-7-4/', 'Pale: Gone Ahead – 7.4', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/15/gone-ahead-7-5/', 'Pale: Gone Ahead – 7.5', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/17/temporary-no-extra-materials/', 'Pale: [Temporary] No extra materials', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/19/gone-ahead-7-6/', 'Pale: Gone Ahead – 7.6', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/22/gone-ahead-7-a/', 'Pale: Gone Ahead – 7.a', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/24/temporary-no-extra-materials-today/', 'Pale: [Temporary] No Extra Materials Today', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/26/gone-ahead-7-7/', 'Pale: Gone Ahead – 7.7', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/29/gone-ahead-7-8/', 'Pale: Gone Ahead – 7.8', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2020/12/31/7-8-spoilers-cwtatg/', 'Pale: [7.8 Spoilers] Can We Talk About The Girls?', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/02/gone-ahead-7-9/', 'Pale: Gone Ahead – 7.9', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/05/gone-ahead-7-x/', 'Pale: Gone Ahead – 7.x', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/07/temporary/', 'Pale: [Temporary] – No extra materials this week', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/09/vanishing-points-8-1/', 'Pale: Vanishing Points – 8.1', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/12/vanishing-points-8-2/', 'Pale: Vanishing Points – 8.2', 6, 'Wildbow');
insert into items (url, title, feed_id, author) values ('https://palewebserial.wordpress.com/2021/01/14/8-2-spoilers-soul-self/', 'Pale: [8.2 Spoilers] Soul & Self', 6, 'Wildbow');
