INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/prologue-2/', 'Prologue', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/book-i-genesis/ ', 'BOOK I: GENESIS', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-1-dark-satanic-mills/', '1. Dark Satanic Mills', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%90-the-cracks-in-the-sky/', 'Interlude א: The Cracks In The Sky', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-2-arise-to-spiritual-strife/', '2. Arise To Spiritual Strife', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%91-the-code-of-the-world/', 'Interlude ב: The Code of the World', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-3-on-a-cloud-i-saw-a-child/', '3. On A Cloud I Saw A Child', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-4-tools-were-made-and-born-were-hands/', '4. Tools Were Made And Born Were Hands', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-5-never-seek-to-tell-thy-love/', '5. Never Seek To Tell Thy Love', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%92-cantors-and-singers/', 'Interlude ג: Cantors and Singers', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-6-till-we-have-built-jerusalem/', '6. Till We Have Built Jerusalem', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-7-the-perishing-vegetable-memory/', '7. The Perishing Vegetable Memory', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-8-laughing-to-scorn-thy-laws-and-terrors/', '8. Laughing To Scorn Thy Laws And Terrors', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-9-with-art-celestial/', '9. With Art Celestial', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-10-bring-the-swift-arrows-of-light/', '10. Bring The Swift Arrows Of Light', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%93-n-grammata/', 'Interlude ד: N-Grammata', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-11-drive-the-just-man-into-barren-climes/', '11. Drive The Just Man Into Barren Climes', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%94-the-right-hand-of-god/', 'Interlude ה: The Right Hand Of God', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-12-borne-on-angels-wings/', '12. Borne On Angels’ Wings', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%95-theres-a-hole-in-my-bucket', 'Interlude ו: There’s A Hole In My Bucket', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-13-the-image-of-eternal-death/', '13. The Image Of Eternal Death', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-14-cruelty-has-a-human-heart/', '14. Cruelty Has A Human Heart', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-15-o-where-shall-i-hide-my-face/', '15. O Where Shall I Hide My Face', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-16-if-perchance-with-iron-power-he-might-avert-his-own-despair/', '16. If Perchance With Iron Power He Might Avert His Own Despair', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%96-man-on-the-sphere/', 'Interlude ז: Man On The Sphere', 4, 'Scott Alexander');

INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/book-2-exodus/', 'BOOK II: EXODUS', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-18-no-earthly-parents-i-confess/', '17. No Earthly Parents I Confess', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-17-that-the-children-of-jerusalem-may-be-saved-from-slavery/', '18. That The Children Of Jerusalem May Be Saved From Slavery', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-19-the-form-of-the-angelic-land/', '19. The Form Of The Angelic Land', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-20-when-the-stars-threw-down-their-spears/', '20. When The Stars Threw Down Their Spears', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-21-thou-also-dwellest-in-eternity/', '21. Thou Also Dwellest In Eternity', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%97-war-and-peace/', 'Interlude ח: War And Peace', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-22-whose-ears-have-heard-the-holy-word/', '22. Whose Ears Have Heard The Holy Word', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-23-now-descendeth-out-of-heaven-a-city/', '23. Now Descendeth Out Of Heaven A City', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%98-the-general-assembly/', 'Interlude ט: The General Assembly', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-24-why-dost-thou-come-to-angels-eyes/', '24. Why Dost Thou Come To Angels’ Eyes', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-25-lie-down-before-my-feet-o-dragon/', '25. Lie Down Before My Feet, O Dragon', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%99-the-broadcast/', 'Interlude י: The Broadcast', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-26-for-not-one-sparrow-can-suffer-and-the-whole-universe-not-suffer-also/', '26. For Not One Sparrow Can Suffer And The Whole Universe Not Suffer Also', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%9B-the-outer-gate/', 'Interlude כ: The Outer Gate', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-27-the-starry-floor-the-watery-shore/', '27. The Starry Floor, The Watery Shore', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-28-hid-as-in-an-ark/', '28. Hid As In An Ark', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%9C-new-york-city/', 'Interlude ל: New York City', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-29-he-who-respects-the-infants-faith/', '29. He Who Respects The Infant’s Faith', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-30-over-the-dark-deserts/', '30. Over The Dark Deserts', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-31-the-foundation-of-empire/', '31. The Foundation Of Empire', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-32-the-human-form-divine/', '32. The Human Form Divine', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-33-the-doors-of-perception/', '33. The Doors Of Perception', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-34-why-wilt-thou-rend-thyself-apart-jerusalem/', '34. Why Wilt Thou Rend Thyself Apart, Jerusalem', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-35-the-voices-of-children-in-his-tents/', '35. The Voices Of Children In His Tents', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-36-my-fathers-business/', '36. My Father’s Business', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%9E-miss-american-pie/', 'Interlude מ: Miss American Pie', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-37-love-that-never-told-can-be/', '37. Love That Never Told Can Be', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-38-i-will-not-cease-from-mental-fight/', '38. I Will Not Cease From Mental Fight', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-39-fearful-symmetry/', '39. Fearful Symmetry', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-40-in-terrible-majesty/', '40. In Terrible Majesty', 4, 'Scott Alexander');

INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/book-iii-revelation/', 'BOOK III: REVELATION', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-41-go-love-without-the-help-of-any-thing-on-earth/', '41. Go Love Without The Help Of Any Thing On Earth', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A0-changelog/', 'Interlude נ: CHANGELOG', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-42-whose-whole-delight-is-in-destroying/', '42. Whose Whole Delight Is In Destroying', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-43-lest-they-be-annihilated-in-thy-annihilation/', '43. Lest They Be Annihilated In Thy Annihilation', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-44-a-world-within-opening-its-gates/', '44. A World Within Opening Its Gates', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-45-in-the-remotest-bottoms-of-the-caves/', '45. In The Remotest Bottoms Of The Caves', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-46-to-talk-of-patience-to-the-afflicted/', '46. To Talk Of Patience To The Afflicted', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-47-for-he-beheld-new-female-forms/', '47. For He Beheld New Female Forms', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-48-bring-me-my-chariot-of-fire/', '48. Bring Me My Chariot Of Fire', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%d7%a1-binary/', 'Interlude ס: Binary', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-49-terrors-of-the-sun-and-moon/', '49. Terrors Of The Sun And Moon', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A4-hell-on-earth/', 'Interlude ע‎: Hell On Earth', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-50-silent-as-despairing-love/', '50. Silent As Despairing Love', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A2%E2%80%8E-eighties-and-nineties/', 'Interludes פ and צ: The 80s And 90s', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-51-he-wondered-that-he-felt-love/', '51. He Wondered That He Felt Love', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-52-the-king-of-light-beheld-her-mourning/', '52. The King Of Light Beheld Her Mourning', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-53-lover-of-wild-rebellion/', '53. Lover Of Wild Rebellion', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A7-bush/', 'Interlude ק: Bush', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-54-my-course-among-the-stars/', '54. My Course Among The Stars', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-55-none-can-visit-his-regions/', '55. None Can Visit His Regions', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A8-the-shrouded-constitution/', 'Interlude ר: The Shrouded Constitution', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-56-agony-in-the-garden/', '56. Agony In The Garden', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%A9-obama/', 'Interlude ש‎: Obama', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-57-now-taking-on-ahanias-form/', '57. Now Taking On Ahania’s Form', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-58-and-now-the-form-of-enion/', '58. And Now The Form Of Enion', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/interlude-%D7%AA-trump/', 'Interlude ת‎: Trump', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-59-clothe-yourself-in-golden-arms/', '59. Clothe Yourself In Golden Arms', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-60-o-rose-thou-art-sick/', '60. O Rose, Thou Art Sick', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-61-and-ololon-said-let-us-descend-also-and-let-us-give-ourselves-to-death-in-ulro-among-the-transgressors/.', '61. And Ololon Said, Let Us Descend Also, And Let Us Give Ourselves To Death In Ulro Among The Transgressors', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-62-that-the-wide-world-might-fly-from-its-hinges/', '62. That The Wide World Might Fly From Its Hinges', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-63-my-wrath-burns-to-the-top-of-heaven/', '63. My Wrath Burns To The Top Of Heaven', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-64-another-better-world-shall-be/', '64. Another Better World Shall Be', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-65-the-fruit-of-my-mysterious-tree/', '65. The Fruit Of My Mysterious Tree', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-66-in-the-forests-of-the-night/', '66. In The Forests Of The Night', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-67-the-night-of-enitharmons-joy/', '67. The Night Of Enitharmon’s Joy', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-68-puts-all-heaven-in-a-rage/', '68. Puts All Heaven In A Rage', 4, 'Scott Alexander');

INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/book-iv-kings/', 'BOOK IV: KINGS', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-69-love-seeketh-not-itself-to-please/', '69. Love Seeketh Not Itself To Please', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-70-nor-for-itself-hath-any-care/', '70. Nor For Itself Hath Any Care', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-71-but-for-another-gives-its-ease/', '71. But For Another Gives Its Ease', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/chapter-72-and-builds-a-heaven-in-hells-despair/', '72. And Builds A Heaven In Hell’s Despair', 4, 'Scott Alexander');
INSERT INTO items (url, title, feed_id, author) values ('https://unsongbook.com/epilogue/', 'Epilogue', 4, 'Scott Alexander');
