INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/07/27/1-00/', 'The Wandering Inn: 1.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/07/27/1-01/', 'The Wandering Inn: 1.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/07/30/1-02/', 'The Wandering Inn: 1.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/07/1-03/', 'The Wandering Inn: 1.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/10/1-04/', 'The Wandering Inn: 1.04', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/13/1-05/', 'The Wandering Inn: 1.05', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/17/1-06/', 'The Wandering Inn: 1.06', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/20/1-07/', 'The Wandering Inn: 1.07', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/24/1-08/', 'The Wandering Inn: 1.08', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/28/1-09/', 'The Wandering Inn: 1.09', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/08/31/1-10/', 'The Wandering Inn: 1.10', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/04/1-11/', 'The Wandering Inn: 1.11', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/04/interlude/', 'The Wandering Inn: Interlude', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/07/1-12/', 'The Wandering Inn: 1.12', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/11/1-13/', 'The Wandering Inn: 1.13', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/14/1-14/', 'The Wandering Inn: 1.14', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/18/1-15/', 'The Wandering Inn: 1.15', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/21/1-16/', 'The Wandering Inn: 1.16', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/25/1-17/', 'The Wandering Inn: 1.17', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/09/28/1-18/', 'The Wandering Inn: 1.18', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/02/1-19/', 'The Wandering Inn: 1.19', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/05/1-20/', 'The Wandering Inn: 1.20', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/06/interlude-1-00-r/', 'The Wandering Inn: Interlude – 1.00 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/12/1-01-r/', 'The Wandering Inn: 1.01 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/16/1-21/', 'The Wandering Inn: 1.21', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/19/1-22/', 'The Wandering Inn: 1.22', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/23/1-23/', 'The Wandering Inn: 1.23', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/26/interlude-king-edition/', 'The Wandering Inn: Interlude: King Edition', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/10/30/1-24/', 'The Wandering Inn: 1.24', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/02/1-02-r/', 'The Wandering Inn: 1.02 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/06/1-03-r/', 'The Wandering Inn: 1.03 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/09/1-25/', 'The Wandering Inn: 1.25', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/13/1-26/', 'The Wandering Inn: 1.26', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/16/1-27/', 'The Wandering Inn: 1.27', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/20/1-04-r/', 'The Wandering Inn: 1.04 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/23/1-05-r/', 'The Wandering Inn: 1.05 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/27/1-28/', 'The Wandering Inn: 1.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/11/30/1-06-r/', 'The Wandering Inn: 1.06 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/04/1-29/', 'The Wandering Inn: 1.29', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/07/1-30/', 'The Wandering Inn: 1.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/11/1-31/', 'The Wandering Inn: 1.31', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/14/1-07-r/', 'The Wandering Inn: 1.07 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/18/1-08-r/', 'The Wandering Inn: 1.08 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/21/1-32/', 'The Wandering Inn: 1.32', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/25/1-33/', 'The Wandering Inn: 1.33', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2016/12/28/1-09-r/', 'The Wandering Inn: 1.09 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/01/1-10-r/', 'The Wandering Inn: 1.10 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/04/1-34/', 'The Wandering Inn: 1.34', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/08/1-35/', 'The Wandering Inn: 1.35', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/11/1-11-r/', 'The Wandering Inn: 1.11 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/15/1-12-r/', 'The Wandering Inn: 1.12 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/18/1-36/', 'The Wandering Inn: 1.36', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/22/1-37/', 'The Wandering Inn: 1.37', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/25/1-38/', 'The Wandering Inn: 1.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/29/1-39/', 'The Wandering Inn: 1.39', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/01/31/1-40/', 'The Wandering Inn: 1.40', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/05/1-13-r/', 'The Wandering Inn: 1.13 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/07/1-41/', 'The Wandering Inn: 1.41', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/12/1-00-h/', 'The Wandering Inn: 1.00 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/15/1-01-h/', 'The Wandering Inn: 1.01 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/19/1-02-h/', 'The Wandering Inn: 1.02 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/22/1-42/', 'The Wandering Inn: 1.42', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/02/25/1-43/', 'The Wandering Inn: 1.43', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/01/1-44/', 'The Wandering Inn: 1.44', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/04/1-45/', 'The Wandering Inn: 1.45', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/07/interlude-2/', 'The Wandering Inn: Interlude', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/12/2-01/', 'The Wandering Inn: 2.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/15/2-02/', 'The Wandering Inn: 2.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/18/2-03/', 'The Wandering Inn: 2.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/22/2-04/', 'The Wandering Inn: 2.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/25/2-05/', 'The Wandering Inn: 2.04', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/03/28/2-06/', 'The Wandering Inn: 2.05', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/02/2-07/', 'The Wandering Inn: 2.06', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/04/2-08/', 'The Wandering Inn: 2.07', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/09/2-09/', 'The Wandering Inn: 2.08', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/12/2-10/', 'The Wandering Inn: 2.09', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/12/2-00-t/', 'The Wandering Inn: 2.10 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/13/2-11/', 'The Wandering Inn: 2.11 ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/14/2-12/', 'The Wandering Inn: 2.12 ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/15/2-13/', 'The Wandering Inn: 2.13 ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/16/2-00-g/', 'The Wandering Inn: 2.14 G ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/17/side-story-mating-rituals/', 'The Wandering Inn: S01 – Mating Rituals ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/18/2-14/', 'The Wandering Inn: 2.15', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/22/2-15/', 'The Wandering Inn: 2.16', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/22/2-16/', 'The Wandering Inn: 2.17', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/25/2-17/', 'The Wandering Inn: 2.18', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/27/2-01-g/', 'The Wandering Inn: 2.19 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/29/2-18/', 'The Wandering Inn: 2.20', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/03/2-19/', 'The Wandering Inn: 2.21', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/05/2-00-k/', 'The Wandering Inn: 2.22 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/07/2-20/', 'The Wandering Inn: 2.23', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/10/2-01-t/', 'The Wandering Inn: 2.24 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/14/2-21/', 'The Wandering Inn: 2.25', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/17/2-22/', 'The Wandering Inn: 2.26', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/25/1-00-c/', 'The Wandering Inn: 1.00 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/04/26/1-01-c/', 'The Wandering Inn: 1.01 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/21/2-02-g/', 'The Wandering Inn: 2.27 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/24/2-23/', 'The Wandering Inn: 2.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/26/2-24/', 'The Wandering Inn: 2.29', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/28/2-25/', 'The Wandering Inn: 2.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/31/2-26/', 'The Wandering Inn: 2.31', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/04/2-00-h/', 'The Wandering Inn: 2.32 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/07/2-27/', 'The Wandering Inn: 2.33', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/09/2-28/', 'The Wandering Inn: 2.34', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/11/2-29/', 'The Wandering Inn: 2.35', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/14/2-03-g/', 'The Wandering Inn: 2.36 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/18/2-30/', 'The Wandering Inn: 2.37', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/21/2-31/', 'The Wandering Inn: 2.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/24/interlude-3/', 'The Wandering Inn: Interlude', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/28/s02-the-antinium-wars-pt-1/', 'The Wandering Inn: S02 – The Antinium Wars (Pt.1)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/05/31/s02-the-antinium-wars-pt-2/', 'The Wandering Inn: S02 – The Antinium Wars (Pt.2)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/27/2-32/', 'The Wandering Inn: 2.39', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/01/2-33/', 'The Wandering Inn: 2.40', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/04/2-34/', 'The Wandering Inn: 2.41', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/08/2-35/', 'The Wandering Inn: 2.42', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/11/2-36/', 'The Wandering Inn: 2.43', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/15/2-37/', 'The Wandering Inn: 2.44', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/18/2-38/', 'The Wandering Inn: 2.45', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/06/30/s03-wistram-days-pt-1/', 'The Wandering Inn: S03 – Wistram Days (Pt. 1)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/22/2-39/', 'The Wandering Inn: 2.46', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/25/2-40/', 'The Wandering Inn: 2.47', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/29/2-41/', 'The Wandering Inn: 2.48', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/01/3-00-e/', 'The Wandering Inn: 3.00 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/05/3-01-e/', 'The Wandering Inn: 3.01 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/08/3-02-h/', 'The Wandering Inn: 3.02 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/12/3-03/', 'The Wandering Inn: 3.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/15/3-04/', 'The Wandering Inn: 3.04', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/19/3-05-l/', 'The Wandering Inn: 3.05 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/14/1-00-d/', 'The Wandering Inn: 1.00 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/07/14/1-01-d/', 'The Wandering Inn: 1.01 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/22/3-06-l/', 'The Wandering Inn: 3.06 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/26/3-07-h/', 'The Wandering Inn: 3.07 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/29/3-08-h/', 'The Wandering Inn: 3.08 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/02/3-09/', 'The Wandering Inn: 3.09', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/05/3-10/', 'The Wandering Inn: 3.10', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/09/3-11-e/', 'The Wandering Inn: 3.11 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/12/3-12-e/', 'The Wandering Inn: 3.12 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/16/3-13/', 'The Wandering Inn: 3.13', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/19/3-14/', 'The Wandering Inn: 3.14', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/23/3-15/', 'The Wandering Inn: 3.15', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/26/3-16', '3.16', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/08/31/s03-wistram-days-pt-2', 'S03 – Wistram Days (Pt. 2)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/27/3-17-t/', 'The Wandering Inn: 3.17 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/28/3-18-t/', 'The Wandering Inn: 3.18 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/09/30/3-19-t/', 'The Wandering Inn: 3.19 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/03/3-20-t/', 'The Wandering Inn: 3.20 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/07/3-21-l/', 'The Wandering Inn: 3.21 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/10/3-22-l/', 'The Wandering Inn: 3.22 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/14/3-23-l/', 'The Wandering Inn: 3.23 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/17/3-24/', 'The Wandering Inn: 3.24', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/21/3-25/', 'The Wandering Inn: 3.25', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/24/3-26-g/', 'The Wandering Inn: 3.26 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/26/3-27-m/', 'The Wandering Inn: 3.27 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/28/3-28-g/', 'The Wandering Inn: 3.28 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/10/31/3-29-g/', 'The Wandering Inn: 3.29 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/04/3-30/', 'The Wandering Inn: 3.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/07/3-31-g/', 'The Wandering Inn: 3.31 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/11/wistram-days-pt-3/', 'The Wandering Inn: S03 – Wistram Days (Pt. 3)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/12/wistram-days-pt-4/', 'The Wandering Inn: S03 – Wistram Days (Pt. 4)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/14/wistram-days-pt-5/', 'The Wandering Inn: S03 – Wistram Days (Pt. 5)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/18/wistram-days-pt-6/', 'The Wandering Inn: S03 – Wistram Days (Pt. 6)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/21/wistram-days-pt-7/', 'The Wandering Inn: S03 – Wistram Days (Pt. 7)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/25/3-32/', 'The Wandering Inn: 3.32', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/11/28/3-33/', 'The Wandering Inn: 3.33', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/02/3-34/', 'The Wandering Inn: 3.34', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/05/3-35/', 'The Wandering Inn: 3.35', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/09/3-36/', 'The Wandering Inn: 3.36', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/12/3-37/', 'The Wandering Inn: 3.37', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/16/3-38/', 'The Wandering Inn: 3.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/19/3-39/', 'The Wandering Inn: 3.39', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/23/3-40/', 'The Wandering Inn: 3.40', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/25/3-41', '3.41', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/26/3-42/', 'The Wandering Inn: 3.42', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2017/12/30/interlude-4/', 'The Wandering Inn: Interlude', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/06/4-00-k/', 'The Wandering Inn: 4.00 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/09/4-01-k/', 'The Wandering Inn: 4.01 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/13/4-02-k/', 'The Wandering Inn: 4.02 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/16/4-03-k/', 'The Wandering Inn: 4.03 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/20/4-04-k/', 'The Wandering Inn: 4.04 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/23/4-05-k/', 'The Wandering Inn: 4.05 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/27/4-06-km/', 'The Wandering Inn: 4.06 KM', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/01/30/4-07/', 'The Wandering Inn: 4.07', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/01/4-08-t/', 'The Wandering Inn: 4.08 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/03/4-09/', 'The Wandering Inn: 4.09', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/06/4-10/', 'The Wandering Inn: 4.10', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/10/4-11/', 'The Wandering Inn: 4.11', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/13/4-12/', 'The Wandering Inn: 4.12', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/17/4-13-l/', 'The Wandering Inn: 4.13 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/20/4-14-l/', 'The Wandering Inn: 4.14 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/20/4-15-l/', 'The Wandering Inn: 4.15 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/24/4-16/', 'The Wandering Inn: 4.16', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/02/27/4-17/', 'The Wandering Inn: 4.17', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/01/1-02-d/', 'The Wandering Inn: 1.02 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/03/1-03-d/', 'The Wandering Inn: 1.03 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/06/1-04-d/', 'The Wandering Inn: 1.04 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/06/1-05-d/', 'The Wandering Inn: 1.05 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/10/1-06-d/', 'The Wandering Inn: 1.06 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/13/4-18/', 'The Wandering Inn: 4.18', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/17/4-19/', 'The Wandering Inn: 4.19', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/20/4-20-e/', 'The Wandering Inn: 4.20 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/24/4-21-e/', 'The Wandering Inn: 4.21 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/27/4-22-e/', 'The Wandering Inn: 4.22 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/27/4-23-e/', 'The Wandering Inn: 4.23 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/03/31/4-24/', 'The Wandering Inn: 4.24', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/03/4-25-n/', 'The Wandering Inn: 4.25 N', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/07/4-26-m/', 'The Wandering Inn: 4.26 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/10/4-27-h/', 'The Wandering Inn: 4.27 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/14/4-28/', 'The Wandering Inn: 4.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/17/4-29/', 'The Wandering Inn: 4.29', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/21/4-30/', 'The Wandering Inn: 4.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/24/4-31/', 'The Wandering Inn: 4.31', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/04/28/4-32-g/', 'The Wandering Inn: 4.32 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/01/1-02-d-2/', 'The Wandering Inn: 1.02 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/01/1-03-d-2/', 'The Wandering Inn: 1.03 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/05/1-04-c/', 'The Wandering Inn: 1.04 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/05/1-05-c/', 'The Wandering Inn: 1.05 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/08/4-33/', 'The Wandering Inn: 4.33', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/12/4-34/', 'The Wandering Inn: 4.34', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/15/4-35-e/', 'The Wandering Inn: 4.35 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/17/4-36-o/', 'The Wandering Inn: 4.36 O', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/19/4-37-o/', 'The Wandering Inn: 4.37 O', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/22/4-38-n/', 'The Wandering Inn: 4.38 B', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/26/4-39-g/', 'The Wandering Inn: 4.39 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/05/29/4-40-l/', 'The Wandering Inn: 4.40 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/02/4-41-l/', 'The Wandering Inn: 4.41 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/02/4-42-l/', 'The Wandering Inn: 4.42 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/05/4-43/', 'The Wandering Inn: 4.43', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/09/4-44-m/', 'The Wandering Inn: 4.44 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/12/4-45/', 'The Wandering Inn: 4.45', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/16/4-46/', 'The Wandering Inn: 4.46', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/19/4-47/', 'The Wandering Inn: 4.47', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/23/s02-the-antinium-wars-pt-3/', 'The Wandering Inn: S02 – The Antinium Wars (Pt.3)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/26/s02-the-antinium-wars-pt-4/', 'The Wandering Inn: S02 – The Antinium Wars (Pt.4)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/26/s02-the-antinium-wars-pt-5/', 'The Wandering Inn: S02 – The Antinium Wars (Pt.5)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/06/29/4-48/', 'The Wandering Inn: 4.48', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/07/4-49/', 'The Wandering Inn: 4.49', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/09/the-depthless-doctor/', 'The Wandering Inn: The Depthless Doctor', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/19/glossary', 'Glossary', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/10/5-00/', 'The Wandering Inn: 5.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/14/5-01/', 'The Wandering Inn: 5.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/17/5-02/', 'The Wandering Inn: 5.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/21/5-03/', 'The Wandering Inn: 5.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/21/5-04/', 'The Wandering Inn: 5.04', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/24/5-05/', 'The Wandering Inn: 5.05', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/27/5-06-m/', 'The Wandering Inn: 5.06 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/28/5-07/', 'The Wandering Inn: 5.07', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/07/31/5-08/', 'The Wandering Inn: 5.08', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/04/interlude-flos/', 'The Wandering Inn: Interlude – Flos', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/07/5-09-e/', 'The Wandering Inn: 5.09 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/11/5-10-e/', 'The Wandering Inn: 5.10 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/14/5-11-e/', 'The Wandering Inn: 5.11 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/18/5-12/', 'The Wandering Inn: 5.12', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/21/5-13/', 'The Wandering Inn: 5.13', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/25/5-14/', 'The Wandering Inn: 5.14', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/08/28/5-15/', 'The Wandering Inn: 5.15', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/01/5-16-s/', 'The Wandering Inn: 5.16 S', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/01/5-17-s/', 'The Wandering Inn: 5.17 S', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/04/5-18-s//', 'The Wandering Inn: 5.18 S', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/08/5-19-g/', 'The Wandering Inn: 5.19 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/11/5-20-g/', 'The Wandering Inn: 5.20 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/15/5-21-e/', 'The Wandering Inn: 5.21 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/18/5-22-g/', 'The Wandering Inn: 5.22 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/22/5-23-g/', 'The Wandering Inn: 5.23 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/09/29/5-24-l/', 'The Wandering Inn: 5.24 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/02/5-25-l/', 'The Wandering Inn: 5.25 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/06/5-26-l/', 'The Wandering Inn: 5.26 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/09/5-27/', 'The Wandering Inn: 5.27', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/13/5-28/', 'The Wandering Inn: 5.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/16/5-29/', 'The Wandering Inn: 5.29', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/20/5-30-g/', 'The Wandering Inn: 5.30 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/23/5-31-g/', 'The Wandering Inn: 5.31 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/27/5-32-g/', 'The Wandering Inn: 5.32 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/10/30/5-33-b/', 'The Wandering Inn: 5.33 B', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/01/interlude-blackmage/', 'The Wandering Inn: Interlude – Blackmage', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/03/5-34/', 'The Wandering Inn: 5.34', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/06/5-35-h/', 'The Wandering Inn: 5.35 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/10/5-36/', 'The Wandering Inn: 5.36', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/13/5-37-g/', 'The Wandering Inn: 5.37 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/17/5-38/', 'The Wandering Inn: 5.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/20/5-39//', 'The Wandering Inn: 5.39', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/24/5-40', '5.40', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/11/27/5-41/', 'The Wandering Inn: 5.41', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/01/5-42/', 'The Wandering Inn: 5.42', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/04/5-43/', 'The Wandering Inn: 5.43', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/06/interlude-niers/', 'The Wandering Inn: Interlude – Niers', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/08/5-44/', 'The Wandering Inn: 5.44', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/11/5-45/', 'The Wandering Inn: 5.45', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/15/5-46/', 'The Wandering Inn: 5.46', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/18/5-47-g/', 'The Wandering Inn: 5.47 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/22/5-48-g/', 'The Wandering Inn: 5.48 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/25/5-49/', 'The Wandering Inn: 5.49', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/29/5-50-g/', 'The Wandering Inn: 5.50 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2018/12/30/interlude-bird/', 'The Wandering Inn: Interlude – Bird', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/08/5-51-g/', 'The Wandering Inn: 5.51 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/12/5-52/', 'The Wandering Inn: 5.52', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/15/5-53/', 'The Wandering Inn: 5.53', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/19/5-54/', 'The Wandering Inn: 5.54 (Non-Canon)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/22/5-54-2/', 'The Wandering Inn: 5.54', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/26/interlude-krshia/', 'The Wandering Inn: Interlude – Krshia', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/01/29/5-55-g/', 'The Wandering Inn: 5.55 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/02/5-56-g/', 'The Wandering Inn: 5.56 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/05/5-57/', 'The Wandering Inn: 5.57', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/09/5-58/', 'The Wandering Inn: 5.58', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/12/5-59/', 'The Wandering Inn: 5.59', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/16/interlude-pebblesnatch-and-garry/', 'The Wandering Inn: Interlude – Pebblesnatch and Garry', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/16/5-60/', 'The Wandering Inn: 5.60', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/19/5-61/', 'The Wandering Inn: 5.61', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/02/26/5-62/', 'The Wandering Inn: 5.62', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/03/02/interlude-5/', 'The Wandering Inn: Interlude', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/03/19/6-00/', 'The Wandering Inn: 6.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/03/23/6-01/', 'The Wandering Inn: 6.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/03/26/6-02/', 'The Wandering Inn: 6.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/03/30/6-03/', 'The Wandering Inn: 6.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/02/6-04-d/', 'The Wandering Inn: 6.04 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/06/6-05-d/', 'The Wandering Inn: 6.05 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/09/6-06-d/', 'The Wandering Inn: 6.06 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/13/6-07-d/', 'The Wandering Inn: 6.07 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/16/6-08/', 'The Wandering Inn: 6.08', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/20/6-09/', 'The Wandering Inn: 6.09', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/23/6-10/', 'The Wandering Inn: 6.10', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/27/6-11/', 'The Wandering Inn: 6.11', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/04/30/6-12-k/', 'The Wandering Inn: 6.12 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/04/6-13-k/', 'The Wandering Inn: 6.13 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/07/6-14-k/', 'The Wandering Inn: 6.14 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/11/6-15-k/', 'The Wandering Inn: 6.15 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/14/6-16/', 'The Wandering Inn: 6.16', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/18/6-17-s/', 'The Wandering Inn: 6.17 S', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/21/6-18-h/', 'The Wandering Inn: 6.18 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/25/6-19-h/', 'The Wandering Inn: 6.19 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/05/28/6-20-d/', 'The Wandering Inn: 6.20 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/01/5-21-d/', 'The Wandering Inn: 6.21 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/04/6-22-d/', 'The Wandering Inn: 6.22 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/08/6-23-d/', 'The Wandering Inn: 6.23 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/11/6-24-d/', 'The Wandering Inn: 6.24 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/15/6-25/', 'The Wandering Inn: 6.25', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/18/6-26/', 'The Wandering Inn: 6.26', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/22/6-27-m/', 'The Wandering Inn: 6.27 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/25/6-28/', 'The Wandering Inn: 6.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/06/29/6-29/', 'The Wandering Inn: 6.29', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/02/interlude-embria/', 'The Wandering Inn: Interlude – Embria', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/13/6-30/', 'The Wandering Inn: 6.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/16/6-31/', 'The Wandering Inn: 6.31', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/20/6-32/', 'The Wandering Inn: 6.32', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/23/6-33-e/', 'The Wandering Inn: 6.33 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/27/6-34-e/', 'The Wandering Inn: 6.34 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/07/30/interlude-numbtongue-pt-1/', 'The Wandering Inn: Interlude – Numbtongue (Pt.1)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/03/interlude-numbtongue-pt-2/', 'The Wandering Inn: Interlude – Numbtongue (Pt.2)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/06/6-35/', 'The Wandering Inn: 6.35', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/10/6-36-e/', 'The Wandering Inn: 6.36 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/13/6-37-e/', 'The Wandering Inn: 6.37 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/17/6-38/', 'The Wandering Inn: 6.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/20/6-39/', 'The Wandering Inn: 6.39', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/24/6-40-e/', 'The Wandering Inn: 6.40 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/27/6-41-e/', 'The Wandering Inn: 6.41 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/08/31/interlude-two-rats/', 'The Wandering Inn: Interlude – Two Rats', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/03/interlude-rufelt/', 'The Wandering Inn: Interlude – Rufelt', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/07/6-42-e/', 'The Wandering Inn: 6.42 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/10/6-43-e/', 'The Wandering Inn: 6.43 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/14/6-44-e/', 'The Wandering Inn: 6.44 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/17/6-45-e/', 'The Wandering Inn: 6.45 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/21/6-46-e/', 'The Wandering Inn: 6.46 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/09/24/6-47-e/', 'The Wandering Inn: 6.47 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/12/6-48-t/', 'The Wandering Inn: 6.48 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/15/6-49/', 'The Wandering Inn: 6.49', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/19/6-50-i/', 'The Wandering Inn: 6.50 I', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/22/6-51-a/', 'The Wandering Inn: 6.51 A', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/26/6-52-k/', 'The Wandering Inn: 6.52 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/10/29/6-53-k/', 'The Wandering Inn: 6.53 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/02/6-54-k/', 'The Wandering Inn: 6.54 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/05/6-55-k/', 'The Wandering Inn: 6.55 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/09/interlude-the-titans-question/', 'The Wandering Inn: Interlude – The Titan’s Question', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/12/6-56/', 'The Wandering Inn: 6.56', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/16/6-57/', 'The Wandering Inn: 6.57', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/19/6-58/', 'The Wandering Inn: 6.58', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/23/6-59/', 'The Wandering Inn: 6.59', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/26/6-60/', 'The Wandering Inn: 6.60', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/11/30/interlude-talia/', 'The Wandering Inn: Interlude – Talia', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/03/6-61-l/', 'The Wandering Inn: 6.61 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/07/6-62-l/', 'The Wandering Inn: 6.62 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/11/interlude-foliana/', 'The Wandering Inn: Interlude – Foliana', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/14/6-63-p/', 'The Wandering Inn: 6.63 P', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/18/6-64/', 'The Wandering Inn: 6.64', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/22/6-65/', 'The Wandering Inn: 6.65', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/25/6-66-h/', 'The Wandering Inn: 6.66 H', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2019/12/29/6-67/', 'The Wandering Inn: 6.67', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/01/6-68/', 'The Wandering Inn: 6.68', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/19/7-00/', 'The Wandering Inn: 7.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/22/7-01/', 'The Wandering Inn: 7.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/26/7-02/', 'The Wandering Inn: 7.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/29/7-03/', 'The Wandering Inn: 7.03', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/01/30/mini-stories-crabs-and-drinks/', 'The Wandering Inn: Mini Chapter #1', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/01/7-04/', 'The Wandering Inn: 7.04', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/04/interlude-queens-and-dragons/', 'The Wandering Inn: Interlude – Queens and Dragons', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/09/7-05-p/', 'The Wandering Inn: 7.05 P', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/12/7-06/', 'The Wandering Inn: 7.06', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/16/7-07', '7.07', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/19/7-08-k/', 'The Wandering Inn: 7.08 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/23/7-09-k/', 'The Wandering Inn: 7.09 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/02/26/7-10-k/', 'The Wandering Inn: 7.10 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/01/7-11/', 'The Wandering Inn: 7.11', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/03/interlude-dancing-and-brawling/', 'The Wandering Inn: Interlude – Dancing and Brawling', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/04/interlude-chocolate-gold/', 'The Wandering Inn: Interlude – Chocolate Gold', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/05/interlude-chess-and-ships/', 'The Wandering Inn: Interlude – Chess and Ships', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/06/interlude-chocolate-alchemy', 'Interlude – Chocolate Alchemy', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/07/interlude-lifting-ants', 'Interlude – Lifting Ants', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/08/interlude-burning-alcohol/', 'The Wandering Inn: Interlude – Burning Alcohol', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/09/interlude-the-hangover-after', 'Interlude – The Hangover After', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/15/7-12-g/', 'The Wandering Inn: 7.12 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/18/7-13-k/', 'The Wandering Inn: 7.13 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/21/mating-rituals-pt-2', 'Mating Rituals Pt.2', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/24/7-14-t/', 'The Wandering Inn: 7.14 T', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/29/7-15-r/', 'The Wandering Inn: 7.15 R', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/03/31/7-16-l', '7.16 L', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/12/7-17-s/', 'The Wandering Inn: 7.17 S', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/15/7-18-m/', 'The Wandering Inn: 7.18 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/19/interlude-strategists-at-sea-pt-1/', 'The Wandering Inn: Interlude – Strategists at Sea (Pt. 1)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/22/interlude-strategists-at-sea-pt-2/', 'The Wandering Inn: Interlude – Strategists at Sea (Pt. 2)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/26/7-19/', 'The Wandering Inn: 7.19', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/04/29/7-20/', 'The Wandering Inn: 7.20', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/03/interlude-a-night-in-the-inn/', 'The Wandering Inn: Interlude – A Night in the Inn', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/06/7-21-kq/', 'The Wandering Inn: 7.21 KQ', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/10/7-22-d', '7.22 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/13/7-23-lm/', 'The Wandering Inn: 7.23 LM', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/24/7-24/', 'The Wandering Inn: 7.24', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/27/7-25/', 'The Wandering Inn: 7.25', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/05/31/7-26/', 'The Wandering Inn: 7.26', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/03/7-27/', 'The Wandering Inn: 7.27', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/07/interlude-the-gecko-of-illusions/', 'The Wandering Inn: Interlude – The Gecko of Illusions', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/10/7-28/', 'The Wandering Inn: 7.28', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/14/7-29-b/', 'The Wandering Inn: 7.29 B', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/24/7-30/', 'The Wandering Inn: 7.30', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/06/28/7-31/', 'The Wandering Inn: 7.31', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/01/interlude-a-meeting-of-druids/', 'The Wandering Inn: Interlude – A Meeting of [Druids]', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/05/7-32-d/', 'The Wandering Inn: 7.32 D', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/08/7-33-i/', 'The Wandering Inn: 7.33 I', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/12/7-34-c/', 'The Wandering Inn: 7.34 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/15/7-35-c/', 'The Wandering Inn: 7.35 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/19/7-36-c/', 'The Wandering Inn: 7.36 C', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/07/29/7-37/', 'The Wandering Inn: 7.37', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/02/7-38/', 'The Wandering Inn: 7.38', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/05/7-39-a/', 'The Wandering Inn: 7.39 A', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/08/interlude-carriages-and-conversations/', 'The Wandering Inn: Interlude – Carriages and Conversations', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/09/interlude-meetings-and-friendships/', 'The Wandering Inn: Interlude – Meetings and Friendships', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/10/interlude-sand-and-notes/', 'The Wandering Inn: Interlude – Sand and Notes', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/11/7-40-er/', 'The Wandering Inn: 7.40 ER', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/12/interlude-food-and-growth/', 'The Wandering Inn: Interlude – Food and Growth', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/13/7-41/', 'The Wandering Inn: 7.41', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/08/14/7-42-m/', 'The Wandering Inn: 7.42 M', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/02/7-43-g/', 'The Wandering Inn: 7.43 G', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/06/7-44/', 'The Wandering Inn: 7.44', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/09/7-45/', 'The Wandering Inn: 7.45', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/13/7-46-k/', 'The Wandering Inn: 7.46 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/16/7-47-k/', 'The Wandering Inn: 7.47 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/20/7-48-k/', 'The Wandering Inn: 7.48 K', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/09/23/7-49/', 'The Wandering Inn: 7.49', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/04/interlude-experiments-in-golems/', 'The Wandering Inn: Interlude – Experiments in Golems', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/07/7-50/', 'The Wandering Inn: 7.50', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/11/7-51/', 'The Wandering Inn: 7.51', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/14/7-52/', 'The Wandering Inn: 7.52', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/18/7-53/', 'The Wandering Inn: 7.53', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/20/7-54/', 'The Wandering Inn: 7.54', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/10/25/7-55-e/', 'The Wandering Inn: 7.55 E', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/04/interlude-saliss-the-adventurer/', 'The Wandering Inn: Interlude – Saliss the Adventurer', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/08/7-56/', 'The Wandering Inn: 7.56', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/11/7-57/', 'The Wandering Inn: 7.57', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/15/7-58/', 'The Wandering Inn: 7.58', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/18/7-59/', 'The Wandering Inn: 7.59', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/22/7-60/', 'The Wandering Inn: 7.60', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/11/25/interlude-the-tribes-of-izril/', 'The Wandering Inn: Interlude – The Tribes of Izril', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/06/interlude-the-innkeepers-knight/', 'The Wandering Inn: Interlude – The Innkeeper’s [Knight]', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/09/7-61/', 'The Wandering Inn: 7.61', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/13/7-62/', 'The Wandering Inn: 7.62', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/16/solstice-pt-1/', 'The Wandering Inn: Solstice (Pt. 1)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/20/solstice-pt-2/', 'The Wandering Inn: Solstice (Pt. 2)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-3/', 'The Wandering Inn: Solstice (Pt. 3)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-4/', 'The Wandering Inn: Solstice (Pt. 4)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-5/', 'The Wandering Inn: Solstice (Pt. 5)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-6/', 'The Wandering Inn: Solstice (Pt. 6)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-7/', 'The Wandering Inn: Solstice (Pt. 7)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-8/', 'The Wandering Inn: Solstice (Pt. 8)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2020/12/23/solstice-pt-9/', 'The Wandering Inn: Solstice (Pt. 9)', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2021/01/10/8-00/', 'The Wandering Inn: 8.00', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2021/01/13/8-01/', 'The Wandering Inn: 8.01', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2021/01/17/8-02/', 'The Wandering Inn: 8.02', 6, 'PirateAba')
INSERT INTO items (url, title, feed_id, author) values ('https://wanderinginn.com/2021/01/20/8-03/', 'The Wandering Inn: 8.03', 6, 'PirateAba')
