INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/21/glow-worm-0-1/', 'Glow-worm - 0.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/24/glow-worm-0-2/', 'Glow-worm - 0.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/26/glow-worm-0-3/', 'Glow-worm - 0.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/28/glow-worm-0-4/', 'Glow-worm - 0.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/31/glow-worm-0-5/', 'Glow-worm - 0.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/10/31/glow-worm-0-6/', 'Glow-worm - 0.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/02/glow-worm-0-7/', 'Glow-worm - 0.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/04/glow-worm-0-8/', 'Glow-worm - 0.8', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/07/glow-worm-0-9/', 'Glow-worm - 0.9', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/09/11/daybreak-1-1/', 'Daybreak – 1.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/14/daybreak-1-2/', 'Daybreak – 1.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/18/daybreak-1-3/', 'Daybreak – 1.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/21/daybreak-1-4/', 'Daybreak – 1.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/25/daybreak-1-5/', 'Daybreak – 1.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/28/daybreak-1-6/', 'Daybreak – 1.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/11/30/daybreak-1-7/', 'Daybreak – 1.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/01/daybreak-1-8/', 'Daybreak – 1.8', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/05/daybreak-interlude-1/', 'Daybreak – Interlude 1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/09/flare-2-1/', 'Flare - 2.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/12/flare-2-2/', 'Flare - 2.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/16/flare-2-3/', 'Flare - 2.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/19/flare-2-4/', 'Flare - 2.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/23/flare-2-5/', 'Flare - 2.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/26/flare-2-6/', 'Flare - 2.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2017/12/30/flare-2-7/', 'Flare - 2.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/02/flare-interlude-2/', 'Flare - Interlude 2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/06/glare-3-1/', 'Glare - 3.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/09/glare-3-2/', 'Glare - 3.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/13/glare-3-3/', 'Glare - 3.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/16/glare-3-4/', 'Glare - 3.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/20/glare-3-5/', 'Glare - 3.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/23/glare-3-6/', 'Glare - 3.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/25/glare-interlude-3/', 'Glare - Interlude 3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/27/shade-4-1/', 'Shade - 4.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/01/30/shade-4-2/', 'Shade - 4.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/03/shade-4-3/', 'Shade - 4.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/06/shade-interlude-4a/', 'Shade - Interlude 4a', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/08/shade-4-4/', 'Shade - 4.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/10/shade-4-5/', 'Shade - 4.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/13/shade-interlude-4b/', 'Shade - Interlude 4b', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/17/shade-4-6/', 'Shade - 4.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/20/shade-4-7/', 'Shade - 4.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/22/shade-interlude-4c/', 'Shade - Interlude 4c', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/24/shadow-5-1/', 'Shadow - 5.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/02/27/shadow-5-2/', 'Shadow - 5.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/03/shadow-5-3/', 'Shadow - 5.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/06/shadow-5-4/', 'Shadow - 5.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/10/shadow-5-5/', 'Shadow - 5.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/13/shadow-interlude-5d/', 'Shadow - Interlude 5d', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/17/shadow-5-6/', 'Shadow - 5.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/20/shadow-5-7/', 'Shadow - 5.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/22/shadow-5-8/', 'Shadow - 5.8', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/24/shadow-5-9/', 'Shadow - 5.9', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/27/shadow-5-10/', 'Shadow - 5.10', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/03/31/shadow-5-11/', 'Shadow - 5.11', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/03/shadow-5-12/', 'Shadow - 5.12', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/07/shadow-interlude-5-x/', 'Shadow - Interlude 5.x', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/10/shadow-interlude-5-y/', 'Shadow - Interlude 5.y', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/14/pitch-6-1/', 'Pitch - 6.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/17/pitch-6-2/', 'Pitch - 6.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/21/pitch-6-3/', 'Pitch - 6.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/24/pitch-6-4/', 'Pitch - 6.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/04/28/pitch-6-5/', 'Pitch - 6.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/01/pitch-6-6/', 'Pitch - 6.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/05/pitch-6-7/', 'Pitch - 6.7', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/08/pitch-6-8/', 'Pitch - 6.8', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/11/pitch-6-9/', 'Pitch - 6.9', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/15/torch-7-1/', 'Torch - 7.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/19/torch-7-2/', 'Torch - 7.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/22/torch-7-3/', 'Torch - 7.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/26/torch-7-4/', 'Torch - 7.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/26/eclipse-x-1/', 'Eclipse - x.1', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/27/eclipse-x-2/', 'Eclipse - x.2', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/28/eclipse-x-3/', 'Eclipse - x.3', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/29/eclipse-x-4/', 'Eclipse - x.4', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/30/eclipse-x-5/', 'Eclipse - x.5', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/05/31/eclipse-x-6/', 'Eclipse - x.6', 1, 'Wildbow');
INSERT INTO items (url, title, feed_id, author) values('https://www.parahumans.net/2018/06/01/eclipse-x-7/', 'Eclipse - x.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/02/eclipse-x-8/', 'Eclipse - X.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/05/torch-7-5/', 'Torch - 7.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/09/torch-7-6/', 'Torch - 7.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/12/torch-7-7/', 'Torch - 7.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/16/torch-7-8/', 'Torch - 7.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/19/torch-7-9/', 'Torch - 7.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/23/torch-7-10/', 'Torch - 7.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/26/torch-interlude-7-x/', 'Torch - 7.x (HSP)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/06/30/torch-7-y/', 'Torch - 7.y (Nieves)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/03/beacon-8-1/', 'Beacon - 8.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/07/beacon-8-2/', 'Beacon - 8.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/10/beacon-8-3/', 'Beacon - 8.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/14/beacon-8-4/', 'Beacon - 8.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/17/beacon-8-5/', 'Beacon - 8.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/21/beacon-8-6/', 'Beacon - 8.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/24/beacon-8-7/', 'Beacon - 8.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/28/beacon-8-8/', 'Beacon - 8.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/07/31/beacon-8-9/', 'Beacon - 8.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/04/beacon-8-10/', 'Beacon - 8.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/07/beacon-8-11/', 'Beacon - 8.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/11/beacon-8-12/', 'Beacon - 8.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/14/beacon-interlude-8-x/', 'Beacon - 8.x (Natalie)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/18/beacon-interlude-8-y/', 'Beacon - 8.y (William)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/21/gleaming-9-1/', 'Gleaming - 9.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/25/gleaming-9-2/', 'Gleaming - 9.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/08/28/gleaming-9-3/', 'Gleaming - 9.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/01/gleaming-9-4/', 'Gleaming - 9.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/04/gleaming-9-5/', 'Gleaming - 9.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/08/gleaming-9-6/', 'Gleaming - 9.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/11/gleaming-9-7/', 'Gleaming - 9.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/13/gleaming-interlude-9-x/', 'Gleaming - 9.x (By)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/15/gleaming-9-8/', 'Gleaming - 9.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/18/gleaming-9-9/', 'Gleaming - 9.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/22/gleaming-interlude-9-y/', 'Gleaming - 9.y (Capricorn)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/25/gleaming-9-10/', 'Gleaming - 9.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/09/29/gleaming-9-11/', 'Gleaming - 9.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/02/gleaming-9-12/', 'Gleaming - 9.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/06/gleaming-9-13/', 'Gleaming - 9.13', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/09/gleaming-9-14/', 'Gleaming - 9.14', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/13/gleaming-9-15/', 'Gleaming - 9.15', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/16/gleaming-interlude-9-z/', 'Gleaming - 9.z (Tristan)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/20/gleaming-interlude-9/', 'Gleaming - 9.i (Ciara)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/23/polarize-10-1/', 'Polarize - 10.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/27/polarize-10-2/', 'Polarize - 10.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/10/30/polarize-10-3/', 'Polarize - 10.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/03/polarize-10-4/', 'Polarize - 10.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/06/polarize-10-5/', 'Polarize - 10.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/10/polarize-10-6/', 'Polarize - 10.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/13/polarize-10-7/', 'Polarize - 10.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/17/polarize-10-8/', 'Polarize - 10.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/20/polarize-10-9/', 'Polarize - 10.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/24/interlude-10-x/', 'Polarize - 10.x (Tats)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/11/27/polarize-10-10/', 'Polarize - 10.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/01/polarize-10-11/', 'Polarize - 10.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/04/polarize-10-12/', 'Polarize - 10.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/08/polarize-10-13/', 'Polarize - 10.13', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/11/interlude-10-y/', 'Polarize - 10.y (Boy in the shell)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/15/interlude-10-z/', 'Polarize - 10.z (Chicken Little)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/18/blinding-11-1/', 'Blinding - 11.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/22/blinding-11-2/', 'Blinding - 11.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/25/blinding-11-3/', 'Blinding - 11.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2018/12/29/interlude-11-a/', 'Blinding - 11.a (Sidepiece)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/01/blinding-11-4/', 'Blinding - 11.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/05/blinding-11-5/', 'Blinding - 11.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/08/blinding-11-6/', 'Blinding - 11.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/12/blinding-11-7/', 'Blinding - 11.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/15/blinding-11-8/', 'Blinding - 11.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/19/interlude-11-b/', 'Blinding - 11.b (Colt)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/22/interlude-11-c/', 'Blinding - 11.c (Darlene)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/26/blinding-11-9/', 'Blinding - 11.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/01/29/blinding-11-10/', 'Blinding - 11.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/02/blinding-11-11/', 'Blinding - 11.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/05/blinding-11-12/', 'Blinding - 11.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/09/interlude-12-z/', 'Heavens - 12.z', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/12/heavens-12-1/', 'Heavens - 12.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/16/heavens-12-2/', 'Heavens - 12.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/19/interlude-12-e/', 'Heavens - 12.e (LL)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/23/heavens-12-3/', 'Heavens - 12.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/02/26/heavens-12-4/', 'Heavens - 12.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/02/heavens-12-all/', 'Heavens - 12.all', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/05/heavens-12-5/', 'Heavens - 12.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/09/heavens-12-6/', 'Heavens - 12.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/12/heavens-12-f/', 'Heavens - 12.f (C)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/16/heavens-12-7/', 'Heavens - 12.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/19/heavens-12-8/', 'Heavens - 12.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/23/heavens-12-9/', 'Heavens - 12.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/26/heavens-12-none/', 'Heavens - 12.none', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/03/29/heavens-12-x/', 'Heavens - 12.x (assorted)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/02/black-13-1/', 'Black - 13.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/05/black-13-2/', 'Black - 13.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/09/black-13-3/', 'Black - 13.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/13/black-13-4/', 'Black - 13.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/16/black-13-5/', 'Black - 13.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/20/black-13-6/', 'Black - 13.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/23/black-13-7/', 'Black - 13.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/27/black-13-8/', 'Black - 13.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/04/27/black-13-8/', 'Black - 13.x (Overseer)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/04/black-13-9/', 'Black - 13.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/07/black-13-10/', 'Black - 13.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/11/black-13-11/', 'Black - 13.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/14/13-z/', 'Black - 13.z', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/18/breaking-14-1/', 'Breaking - 14.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/21/breaking-14-2/', 'Breaking - 14.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/25/breaking-14-3/', 'Breaking - 14.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/05/28/breaking-14-4/', 'Breaking - 14.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/01/breaking-14-5/', 'Breaking - 14.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/04/breaking-14-6/', 'Breaking - 14.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/08/breaking-14-7/', 'Breaking - 14.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/11/breaking-14-8/', 'Breaking - 14.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/15/breaking-14-9/', 'Breaking - 14.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/18/breaking-14-10/', 'Breaking - 14.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/22/breaking-14-11/', 'Breaking - 14.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/25/breaking-14-12/', 'Breaking - 14.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/06/29/breaking-14-z/', 'Breaking - 14.z', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/02/dying-15-a/', 'Dying - 15.a', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/06/dying-15-1/', 'Dying - 15.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/09/dying-15-2/', 'Dying - 15.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/13/dying-15-3/', 'Dying - 15.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/16/dying-15-4/', 'Dying - 15.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/20/dying-15-5/', 'Dying - 15.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/23/dying-15-6/', 'Dying - 15.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/27/dying-15-7/', 'Dying - 15.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/07/30/dying-15-8/', 'Dying - 15.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/03/dying-15-x/', 'Dying - 15.x', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/06/dying-15-y/', 'Dying - 15.y', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/10/dying-15-z/', 'Dying - 15.z', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/13/from-within-16-1/', 'From Within - 16.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/17/from-within-16-2/', 'From Within - 16.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/20/from-within-16-3/', 'From Within - 16.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/24/from-within-16-4/', 'From Within - 16.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/27/from-within-16-5/', 'From Within - 16.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/08/31/from-within-16-6/', 'From Within - 16.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/03/from-within-16-7/', 'From Within - 16.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/07/from-within-16-8/', 'From Within - 16.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/10/from-within-16-9/', 'From Within - 16.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/14/from-within-16-10/', 'From Within - 16.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/17/from-within-16-11/', 'From Within - 16.11', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/21/from-within-16-12/', 'From Within - 16.12', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/24/from-within-16-y/', 'From Within - 16.y (Amy)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/09/28/from-within-16-z/', 'From Within - 16.z (Red Queen)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/01/sundown-17-1/', '(Sundown) - 17.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/05/sundown-17-2/', '(Sundown) - 17.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/08/sundown-17-3/', '(Sundown) - 17.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/12/sundown-17-4/', '(Sundown) - 17.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/15/sundown-17-5/', '(Sundown) - 17.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/19/sundown-17-6/', '(Sundown) - 17.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/22/sundown-17-7/', '(Sundown) - 17.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/26/sundown-17-8/', '(Sundown) - 17.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/10/29/sundown-17-9/', '(Sundown) - 17.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/02/sundown-17-10/', '(Sundown) - 17.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/05/interlude-17-x-sundown/', '(Sundown) - 17.x (Major Malfunctions pt. 1)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/09/interlude-17-y-sundown/', '(Sundown) - 17.y (Major Malfunctions pt. 2)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/12/interlude-17-z-sundown/', '(Sundown) - 17.z (Assorted)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/16/radiation-18-1/', '(Radiation) - 18.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/19/radiation-18-2/', '(Radiation) - 18.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/23/radiation-18-3/', '(Radiation) - 18.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/26/radiation-18-4/', '(Radiation) - 18.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/11/30/radiation-18-5/', '(Radiation) - 18.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/03/radiation-18-6/', '(Radiation) - 18.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/07/radiation-18-7/', '(Radiation) - 18.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/10/radiation-18-8/', '(Radiation) - 18.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/14/radiation-18-9/', '(Radiation) - 18.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/17/radiation-18-10/', '(Radiation) - 18.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/21/interlude-18-z-radiation/', '(Radiation) - 18.z (Titans)', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/24/infrared-19-1/', '(Infrared) - 19.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2019/12/28/infrared-19-2/', '(Infrared) - 19.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/01/interlude-19-a/', '(Infrared) - 19.a', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/04/infrared-19-3/', '(Infrared) - 19.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/07/infrared-19-4/', '(Infrared) - 19.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/11/infrared-19-b/', '(Infrared) - 19.b', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/14/infrared-19-c/', '(Infrared) - 19.c', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/18/infrared-19-5/', '(Infrared) - 19.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/21/infrared-19-6/', '(Infrared) - 19.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/25/infrared-19-d/', '(Infrared) - 19.d', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/01/28/infrared-19-e/', '(Infrared) - 19.e', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/02/infrared-19-7/', '(Infrared) - 19.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/04/infrared-19-8/', '(Infrared) - 19.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/08/infrared-19-9/', '(Infrared) - 19.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/11/infrared-19-f/', '(Infrared) - 19.f', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/15/infrared-19-10/', '(Infrared) - 19.10', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/18/infrared-19-g/', '(Infrared) - 19.g', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/23/infrared-19-z/', '(Infrared) - 19.z', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/25/last-20-1/', '(Last) - 20.1', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/02/29/last-20-2/', '(Last) - 20.2', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/03/last-20-3/', '(Last) - 20.3', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/07/last-20-4/', '(Last) - 20.4', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/10/last-20-5/', '(Last) - 20.5', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/15/last-20-6/', '(Last) - 20.6', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/17/last-20-7/', '(Last) - 20.7', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/21/last-20-8/', '(Last) - 20.8', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/24/last-20-9/', '(Last) - 20.9', 1, 'Wildbow');
INSERT INTO ITEMS (url, title, feed_id, author) values ('https://www.parahumans.net/2020/03/28/last-20-a/', '(Last) - 20.a', 1, 'Wildbow');
